# This workflow will build package, and publish it to pypi.org

name: publish

on:
  release:
    types: [published]

jobs:
  run_image:
    runs-on: [ubuntu-18.04]
    container:
      image: matanrubin/python-poetry:3.7

    steps:
      - uses: actions/checkout@v2
      - run: cd ..
      - run: make bootstrap
      - run: poetry update -vvv
      - run: poetry build -vvv
      # Add repository
      - run: poetry config repositories.test_pypi https://test.pypi.org/simple/

      - run: poetry publish --repository repositories.test_pypi --username __token__ --password ${{ secrets.PYPI_TOKEN }}
