# This workflow will install dependencies, build Pyctuator, run tests (+coverage) and lint

name: check_gh_cd

on:
  push:
  pull_request:

jobs:
  run_image:
    runs-on: [ubuntu-18.04]
    container:
      image: matanrubin/python-poetry:3.7

    steps:
      - uses: actions/checkout@v2
      - run: pwd
      - run: ls -la
      - run: cd environment
        continue-on-error: true
      - run: pwd
      - run: echo "Newfile baby!!" > tests/newfile.txt
      - run: ls -la
      - run: cd tests; ls -la
        continue-on-error: true
      - run: cat newfile.txt
        working-directory: ./tests
      - run: pwd
      - run: ls -la

      - run: cd ..
      - run: pwd
      - run: ls -la
      - run: cd ..
      - run: pwd
      - run: ls -la
##      - run: make bootstrap
##      - run: poetry update -vvv
##      - run: poetry build -vvv
##      - run: poetry install --extras flask --extras fastapi --extras db --extras redis
##      - run: make coverage
#      - uses: actions/upload-artifact@v2
#        with:
#          name: htmlcov.zip
#          path: htmlcov/
#      - uses: codecov/codecov-action@v1

      # Install the extra psutil module and run linting+tests in the "psutil enabled" env
      - run: poetry install --extras psutil
      - run: make check
      - run: make test
